### ISSUE TITLE
Hot-reloading corrupts shaders

### ISSUE THREAD

**Issue by MartinSStewart** [elm-explorations/webgl#17]
Sometimes when hot-reloading the webpage, artifacts can get introduced into the scene such as where the red arrow is pointing
<img width="457" alt="webgl_bug" src="https://user-images.githubusercontent.com/5068391/62685823-ac2e7d80-b9c3-11e9-9265-e9e93028f101.png">
Hot-reloading sometimes also causes entities to not render.

In terms of frequency, the former seems to rarely happen (I delayed posting this issue because I couldn't reproduce it for a couple days) and the latter happens maybe 1 in 5 hot-reloads.

The mesh corruption artifacts don't seem to go away until I do a page refresh while the entities disappearing usually is fixed by doing one or two more hot-reloads.

This is occurring on Chrome both on my Mac and Windows computers. It might have also occurred on Firefox though I might be misremembering as I haven't tested that in a while.

Edit: Now I'm getting the mesh corruption repeatedly. I'm not sure what conditions cause it to happen more frequently.

**Comment by w0rm** [comment]
@MartinSStewart this could have been solved by https://github.com/elm-explorations/webgl/pull/20

Are you still getting this issue?

**Comment by MartinSStewart** [comment]
I haven't seen this issue in almost a month. #20 may have fixed it.
